<!DOCTYPE html>
<html lang="en">



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tienda Charly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="<?= BASE_URL; ?>app/css/style.css">

</head>

<div class="container"></div>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="home">Tienda Charly</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                          <li class="nav-item">
                                <a class="nav-link" href="contacto">Contacto</a>
                            </li>
                        <!-- Mostrar enlaces de navegación solo si el usuario ha iniciado sesión -->
                        <?php
                        
                        AuthHelper::initSession();
                        if (isset($_SESSION['USER_ID'])): ?>
                           
                        
                         
                            <li class="nav-item">
                                <a class="nav-link" href="logout">Cerrar Sesión</a> 
                                
                            </li>
                        <?php endif; ?>

                        <!-- Mostrar enlaces de navegación para registro e inicio de sesión solo si el usuario no ha iniciado sesión -->
                        <?php if (!isset($_SESSION['USER_ID'])): ?>
                            <li class="nav-item">
                                <a class="nav-link" href="registro">Registro</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="login">Iniciar Sesión</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>
    </header>