<section class="container mt-5">
    <h2 class="text-center mb-4">Registro</h2>
    <form action="registro_new_user" method="POST" class="w-50 mx-auto">
        <div class="mb-3">
            <label for="username" class="form-label">Nombre de Usuario</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Ingrese su nombre de usuario" required>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Contraseña</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Ingrese su contraseña" required>
        </div>
        <div class="mb-3">
            <label for="confirm_password" class="form-label">Confirmar Contraseña</label>
            <input type="password" class="form-control" id="confirm_password" name="confirm_password" placeholder="Ingrese su contraseña nuevamente" required>
        </div>
        <button type="submit" class="btn btn-primary w-100">Registrarse</button>
    </form>
</section>